// GALLERY
export const GALLERY_ITEMS = "GALLERY_ITEMS";
export const GALLERY_SHOW = " GALLERY_SHOW";
export const GALLERY_SHOW_ARR = "GALLERY_SHOW_ARR";

// LIBRARY TYPEOF

export const LIBRARY_DEL_CATEGORY = "LIBRARY_DEL_CATEGORY";
export const LIBRARY_CREATE_CATEGORY = "LIBRARY_CREATE_CATEGORY";
export const LIBRARY_GET_CATEGORY = "LIBRARY_GET_CATEGORY";
export const LIBRARY_GET_STATUSES = "LIBRARY_GET_STATUSES";
export const LIBRARY_GET_VISIBILITY = "LIBRARY_GET_VISIBILITY";

// LIBRARY GET DATA
export const LIBRARY_ARTICLES_ANALYZE = "LIBRARY_ARTICLES_ANALYZE";
export const LIBRARY_GET_ARTICLES = "LIBRARY_GET_ARTICLES";
export const LIBRARY_GET_ARTICLES_SINGLE = "LIBRARY_GET_ARTICLES_SINGLE";
export const LIBRARY_DELETE_ARTICLES = "LIBRARY_DELETE_ARTICLES";
export const LIBRARY_BOOKMARK_ARTICLES = "LIBRARY_BOOKMARK_ARTICLES";
export const LIBRARY_BOOKMARK_ARTICLES_DEL = "LIBRARY_BOOKMARK_ARTICLES_DEL";

// LIBRARY GET MY DOCUMENT

export const LIBRARY_GET_MY_DOC = "LIBRARY_GET_MY_DOC";
export const LIBRARY_CREATE_MY_DOC = "LIBRARY_CREATE_MY_DOC";
export const LIBRARY_UPDATE_MY_DOC = "LIBRARY_UPDATE_MY_DOC";
export const LIBRARY_CREATE_BULK = "LIBRARY_CREATE_BULK";

export const LIBRARY_DEL_REF_CODE = "LIBRARY_DEL_REF_CODE";

// LIBRARY GET USER

export const LIBRARY_GET_USER = "LIBRARY_GET_USER";

// PAGE

export const SET_MY_DOCUMENT_PAGE = "SET_MY_DOCUMENT_PAGE";
export const PREV_ROUTES_NAME = "PREV_ROUTES_NAME";
export const ORG_SERVICES = "ORG_SERVICES" 
export const AUTHZ_REQ = "AUTHZ_REQ"

export const IS_403 = "IS_403"
export const AUTH_PROFILE = 'AUTH_PROFILE'